let lista = [
  "Longsword",
  "Shortsword",
  "Broadsword",
  "Barbed Straight Sword",
  "Sunlight Straight Sword",
  "Silver Knight Straight Sword",
  "Astora's Straight Sword",
  "Balder Side Sword",
  "Dark Sword",
  "Claymore",
  "Bastard Sword",
  "Black Knight Sword",
  "Greatsword of Artorias (Normal & Cursed)",
  "Moonlight Greatsword",
  "Flamberge",
  "Man-Serpent Greatsword",
  "Zweihander",
  "Greatsword of the Black Knight",
  "Demon Great Machete",
  "Greatsword of Artorias (Cursed)",
  "Dragon Greatsword",
  "Scimitar",
  "Falchion",
  "Shotel",
  "Painting Guardian Sword",
  "Server",
  "Quelaag's Fury Sword",
  "Uchigatana",
  "Iaito",
  "Washing Pole",
  "Chaos Blade",
  "Rapier",
  "Estoc",
  "Ricard's Rapier",
  "Velka's Rapier",
  "Battle Axe",
  "Hand Axe",
  "Gargoyle Tail Axe",
  "Butcher Knife",
  "Greataxe",
  "Demon's Greataxe",
  "Black Knight Greataxe",
  "Mace",
  "Morning Star",
  "Warpick",
  "Pickaxe",
  "Great Club",
  "Large Club",
  "Demon's Great Hammer",
  "Smough's Hammer",
  "Dragon Tooth",
  "Spear",
  "Winged Spear",
  "Pike",
  "Silver Knight Spear",
  "Demon Spear",
  "Halberd",
  "Gargoyle Halberd",
  "Black Knight Halberd",
  "Lucerne",
  "Giant's Halberd",
  "Short Bow",
  "Longbow",
  "Black Bow of Pharis",
  "Composite Bow",
  "Dragon Slayer Greatbow",
  "Light Crossbow",
  "Heavy Crossbow",
  "Avelyn",
  "Sorcerer's Catalyst",
  "Beatrice's Catalyst",
  "Tin Banishment Catalyst",
  "Logan's Catalyst",
  "Tin Crystallization Catalyst",
  "Izalith Catalyst",
  "Talisman",
  "Canvas Talisman",
  "Ivory Talisman",
  "Sunlight Talisman",
  "Darkmoon Talisman",
  "Pyromancy Flame (and Ascended version)",
  "Heater Shield",
  "Grass Crest Shield",
  "Crest Shield",
  "Dragon Crest Shield",
  "Silver Knight Shield",
  "Black Knight Shield",
  "Tower Shield",
  "Eagle Shield",
  "Havel's Greatshield",
  "Greatshield of Artorias",
  "Balder Shield",
  "Spider Shield",
  "Effigy Shield",
  "Bloodshield",
  "Sanctus",
  "Elite Knight Set",
  "Havel's Set",
  "Black Iron Set",
  "Giant's Set",
  "Ornstein's Set",
  "Smough's Set",
  "Artorias' Set",
  "Silver Knight Set",
  "Black Knight Set",
  "Wanderer Set",
  "Thief Set",
  "Pyromancer Set",
  "Channeler Set",
  "Paladin Set",
  "Crimson Set",
  "Cleric Set",
  'Catarina Set (\\"Onion Knight\\")',
  "Dark Set",
  "Shadow Set",
  "Gold-Hemmed Black Set",
  "Dingy Set",
  "Antiquated Set",
  "Hollow Soldier Set",
  "Painting Guardian Set",
  "Brass Set",
  "Ring of Favor and Protection",
  "Havel's Ring",
  "Wolf Ring",
  "Hornet Ring",
  "Leo Ring",
  "Bellowing Dragoncrest Ring",
  "Dusk Crown Ring",
  "Dark Wood Grain Ring",
  "Cloranthy Ring",
  "Rusted Iron Ring",
  "Covetous Gold Serpent Ring",
  "Covetous Silver Serpent Ring",
  "Slumbering Dragoncrest Ring",
  "Ring of Steel Protection",
  "Speckled Stoneplate Ring",
  "Bloodbite Ring",
  "Poisonbite Ring",
  "Ring of the Evil Eye",
  "Tiny Being's Ring",
  "Orange Charred Ring",
  "Old Witch's Ring",
  "Darkmoon Seance Ring",
  "White Seance Ring",
  "Ring of the Sun Princess",
  "Soul Arrow",
  "Great Soul Arrow",
  "Heavy Soul Arrow",
  "Great Heavy Soul Arrow",
  "Homing Soulmass",
  "Crystal Soulmass",
  "Crystal Soul Spear",
  "Magic Weapon",
  "Great Magic Weapon",
  "Crystal Magic Weapon",
  "Fall Control",
  "Hidden Body",
  "Hush",
  "Magic Shield",
  "Strong Magic Shield",
  "Fireball",
  "Great Fireball",
  "Fire Orb",
  "Combustion",
  "Great Combustion",
  "Fire Whip",
  "Firestorm",
  "Chaos Storm",
  "Fire Tempest",
  "Poison Mist",
  "Toxic Mist",
  "Iron Flesh",
  "Flash Sweat",
  "Power Within",
  "Heal",
  "Great Heal",
  "Great Heal Excerpt",
  "Replenishment",
  "Wrath of the Gods",
  "Lightning Spear",
  "Great Lightning Spear",
  "Sunlight Spear",
  "Force",
  "Homeward",
  "Emit Force",
  "Tranquil Walk of Peace",
  "Magic Barrier",
  "Great Magic Barrier",
  "Master Key",
  "Residence Key",
  "Basement Key",
  "Undead Asylum F2 East Key",
  "Crest of Artorias",
  "Lordvessel",
  "Peculiar Doll",
  "Blighttown Key",
  "Cage Key",
  "Archive Tower Giant Door Key",
  "Big Pilgrim's Key",
  "Cell Key",
  "Annex Key",
  "Crest Key",
  "Dungeon Cell Key",
  "Key to New Londo Ruins",
  "Estus Flask",
  "Humanity",
  "Twin Humanities",
  "Homeward Bone",
  "Green Blossom",
  "Lloyd's Talisman",
  "Firebomb",
  "Black Firebomb",
  "Throwing Knife",
  "Poison Throwing Knife",
  "Dung Pie",
  "Prism Stone",
  "Charcoal Pine Resin",
  "Gold Pine Resin",
  "Rotten Pine Resin",
  "Rubbish",
  "Undead Rapport",
  "Titanite Shard",
  "Large Titanite Shard",
  "Green Titanite Shard",
  "Titanite Chunk",
  "Blue Titanite Chunk",
  "White Titanite Chunk",
  "Red Titanite Chunk",
  "Titanite Slab",
  "Dragon Scale",
  "Demon Titanite",
  "Twinkling Titanite",
  "Soul of Gwyn, Lord of Cinder",
  "Soul of Artorias",
  "Soul of Manus",
  "Soul of Sif",
  "Soul of Quelaag",
  "Soul of Gwyndolin",
  "Soul of the Moonlight Butterfly",
  "Core of an Iron Golem",
  "Soul of Ornstein",
  "Soul of Smough",
  "Guardian Soul",
  "Soul of Priscilla",
];

let searchbar = document.getElementById("searchbar");

for (const element of lista) {
  let ciccione = document.createElement("li");
  ciccione.classList.add("sasso");
  ciccione.innerHTML = `<a target="s" rel="s" href = "https://darksouls.wiki.fextralife.com/${element}">${element}</a>`;
  document.getElementById("list").appendChild(ciccione);
}

function search_item() {
  let input = document.getElementById("searchbar").value;
  input = input.toLowerCase();
  let x = document.getElementsByClassName("sasso");
  for (const mocc of x) {
    if (!mocc.textContent.toLowerCase().includes(input)) {
      mocc.style.display = "none";
    } else {
      mocc.style.display = "list-item";
    }
  }
}
