let lista = [
  "Longsword",
  "Shortsword",
  "Broadsword",
  "Barbed Straight Sword",
  "Sunlight Straight Sword",
  "Silver Knight Straight Sword",
  "Astora's Straight Sword",
  "Balder Side Sword",
  "Dark Sword",
  "Claymore",
  "Bastard Sword",
  "Black Knight Sword",
  "Greatsword of Artorias (Normal & Cursed)",
  "Moonlight Greatsword",
  "Flamberge",
  "Man-Serpent Greatsword",
  "Zweihander",
  "Greatsword of the Black Knight",
  "Demon Great Machete",
  "Greatsword of Artorias (Cursed)",
  "Dragon Greatsword",
  "Scimitar",
  "Falchion",
  "Shotel",
  "Painting Guardian Sword",
  "Server",
  "Quelaag's Fury Sword",
  "Uchigatana",
  "Iaito",
  "Washing Pole",
  "Chaos Blade",
  "Rapier",
  "Estoc",
  "Ricard's Rapier",
  "Velka's Rapier",
  "Battle Axe",
  "Hand Axe",
  "Gargoyle Tail Axe",
  "Butcher Knife",
  "Greataxe",
  "Demon's Greataxe",
  "Black Knight Greataxe",
  "Mace",
  "Morning Star",
  "Warpick",
  "Pickaxe",
  "Great Club",
  "Large Club",
  "Demon's Great Hammer",
  "Smough's Hammer",
  "Dragon Tooth",
  "Spear",
  "Winged Spear",
  "Pike",
  "Silver Knight Spear",
  "Demon Spear",
  "Halberd",
  "Gargoyle Halberd",
  "Black Knight Halberd",
  "Lucerne",
  "Giant's Halberd",
  "Short Bow",
  "Longbow",
  "Black Bow of Pharis",
  "Composite Bow",
  "Dragon Slayer Greatbow",
  "Light Crossbow",
  "Heavy Crossbow",
  "Avelyn",
  "Sorcerer's Catalyst",
  "Beatrice's Catalyst",
  "Tin Banishment Catalyst",
  "Logan's Catalyst",
  "Tin Crystallization Catalyst",
  "Izalith Catalyst",
  "Talisman",
  "Canvas Talisman",
  "Ivory Talisman",
  "Sunlight Talisman",
  "Darkmoon Talisman",
  "Pyromancy Flame (and Ascended version)",
  "Heater Shield",
  "Grass Crest Shield",
  "Crest Shield",
  "Dragon Crest Shield",
  "Silver Knight Shield",
  "Black Knight Shield",
  "Tower Shield",
  "Eagle Shield",
  "Havel's Greatshield",
  "Greatshield of Artorias",
  "Balder Shield",
  "Spider Shield",
  "Effigy Shield",
  "Bloodshield",
  "Sanctus",
  "Elite Knight Set",
  "Havel's Set",
  "Black Iron Set",
  "Giant's Set",
  "Ornstein's Set",
  "Smough's Set",
  "Artorias' Set",
  "Silver Knight Set",
  "Black Knight Set",
  "Wanderer Set",
  "Thief Set",
  "Pyromancer Set",
  "Channeler Set",
  "Paladin Set",
  "Crimson Set",
  "Cleric Set",
  "Catarina Set",
  "Dark Set",
  "Shadow Set",
  "Gold-Hemmed Black Set",
  "Dingy Set",
  "Antiquated Set",
  "Hollow Soldier Set",
  "Painting Guardian Set",
  "Brass Set",
  "Ring of Favor and Protection",
  "Havel's Ring",
  "Wolf Ring",
  "Hornet Ring",
  "Leo Ring",
  "Bellowing Dragoncrest Ring",
  "Dusk Crown Ring",
  "Dark Wood Grain Ring",
  "Cloranthy Ring",
  "Rusted Iron Ring",
  "Covetous Gold Serpent Ring",
  "Covetous Silver Serpent Ring",
  "Slumbering Dragoncrest Ring",
  "Ring of Steel Protection",
  "Speckled Stoneplate Ring",
  "Bloodbite Ring",
  "Poisonbite Ring",
  "Ring of the Evil Eye",
  "Tiny Being's Ring",
  "Orange Charred Ring",
  "Old Witch's Ring",
  "Darkmoon Seance Ring",
  "White Seance Ring",
  "Ring of the Sun Princess",
  "Soul Arrow",
  "Great Soul Arrow",
  "Heavy Soul Arrow",
  "Great Heavy Soul Arrow",
  "Homing Soulmass",
  "Crystal Soulmass",
  "Crystal Soul Spear",
  "Magic Weapon",
  "Great Magic Weapon",
  "Crystal Magic Weapon",
  "Fall Control",
  "Hidden Body",
  "Hush",
  "Magic Shield",
  "Strong Magic Shield",
  "Fireball",
  "Great Fireball",
  "Fire Orb",
  "Combustion",
  "Great Combustion",
  "Fire Whip",
  "Firestorm",
  "Chaos Storm",
  "Fire Tempest",
  "Poison Mist",
  "Toxic Mist",
  "Iron Flesh",
  "Flash Sweat",
  "Power Within",
  "Heal",
  "Great Heal",
  "Great Heal Excerpt",
  "Replenishment",
  "Wrath of the Gods",
  "Lightning Spear",
  "Great Lightning Spear",
  "Sunlight Spear",
  "Force",
  "Homeward",
  "Emit Force",
  "Tranquil Walk of Peace",
  "Magic Barrier",
  "Great Magic Barrier",
  "Master Key",
  "Residence Key",
  "Basement Key",
  "Undead Asylum F2 East Key",
  "Crest of Artorias",
  "Lordvessel",
  "Peculiar Doll",
  "Blighttown Key",
  "Cage Key",
  "Archive Tower Giant Door Key",
  "Big Pilgrim's Key",
  "Cell Key",
  "Annex Key",
  "Crest Key",
  "Dungeon Cell Key",
  "Key to New Londo Ruins",
  "Estus Flask",
  "Humanity",
  "Twin Humanities",
  "Homeward Bone",
  "Green Blossom",
  "Lloyd's Talisman",
  "Firebomb",
  "Black Firebomb",
  "Throwing Knife",
  "Poison Throwing Knife",
  "Dung Pie",
  "Prism Stone",
  "Charcoal Pine Resin",
  "Gold Pine Resin",
  "Rotten Pine Resin",
  "Rubbish",
  "Undead Rapport",
  "Titanite Shard",
  "Large Titanite Shard",
  "Green Titanite Shard",
  "Titanite Chunk",
  "Blue Titanite Chunk",
  "White Titanite Chunk",
  "Red Titanite Chunk",
  "Titanite Slab",
  "Dragon Scale",
  "Demon Titanite",
  "Twinkling Titanite",
  "Soul of Gwyn, Lord of Cinder",
  "Soul of Artorias",
  "Soul of Manus",
  "Soul of Sif",
  "Soul of Quelaag",
  "Soul of Gwyndolin",
  "Soul of the Moonlight Butterfly",
  "Core of an Iron Golem",
  "Soul of Ornstein",
  "Soul of Smough",
  "Guardian Soul",
  "Soul of Priscilla",
];

let lista2 = [
  "Longsword",
  "Broadsword",
  "Bastard Sword",
  "Claymore",
  "Zweihander",
  "Greatsword",
  "Black Knight Greatsword",
  "Drakekeeper's Sword",
  "Blue Flame",
  "Falchion",
  "Scimitar",
  "Shotel",
  "Warped Sword",
  "Curved Dragon Greatsword",
  "Murakumo",
  "Uchigatana",
  "Washing Pole",
  "Blacksteel Katana",
  "Chaos Blade",
  "Rapier",
  "Estoc",
  "Ricard's Rapier",
  "Espada Ropera",
  "Great Rapier",
  "Mace",
  "Morning Star",
  "Reinforced Club",
  "Large Club",
  "Great Club",
  "Santier's Spear",
  "Pike",
  "Partizan",
  "Winged Spear",
  "Heide Spear",
  "Dragonrider's Halberd",
  "Lucerne",
  "Halberd",
  "Blue Knight's Halberd",
  "Black Knight Halberd",
  "Drangleic Shield",
  "Tower Shield",
  "Greatshield of Glory",
  "King's Shield",
  "Havel's Greatshield",
  "Buckler",
  "Small Leather Shield",
  "Target Shield",
  "Elite Knight Armor",
  "Drangleic Armor",
  "Alva Armor",
  "Faraam Armor",
  "Vengarl's Armor",
  "Lion Mage Robe",
  "Hexer's Robes",
  "Saint's Trousers",
  "Wanderer's Hood",
  "Chloranthy Ring",
  "Ring of Blades",
  "Clutch Ring",
  "Third Dragon Ring",
  "Ring of Binding",
  "Life Ring",
  "Ring of Giants",
  "Ring of Thorns",
  "Covetous Silver Serpent Ring",
  "Covetous Gold Serpent Ring",
  "Soul Ring",
  "Ring of Prayer",
  "Estus Flask",
  "Lifegem",
  "Radiant Lifegem",
  "Old Radiant Lifegem",
  "Divine Blessing",
  "Amber Herb",
  "Wilted Dusk Herb",
  "Amber Blossom",
  "Green Blossom",
  "Moss Clump",
  "Poison Moss",
  "Bleeding Serum",
  "Charcoal Pine Resin",
  "Gold Pine Resin",
  "Dark Pine Resin",
  "Magic Stone",
  "Faintstone",
  "Fire Seed",
  "Bonfire Ascetic",
  "Human Effigy",
  "Soul of a Lost Undead",
  "Soul of a Proud Knight",
  "Soul of a Brave Warrior",
  "Soul of a Great Hero",
  "Soul of the Pursuer",
  "Soul of the Rotten",
  "Soul of the Old Iron King",
  "Soul of Nashandra",
  "Soul of the King",
  "Smelter Demon Soul",
  "Old Witch Soul",
  "Old Paledrake Soul",
  "Old Dead One Soul",
  "Key to the King's Passage",
  "Brightstone Key",
  "Forgotten Key",
  "Fragrant Branch of Yore",
  "Dull Ember",
  "Petrified Something",
  "Estus Flask Shard",
  "Sublime Bone Dust",
  "Titanite Shard",
  "Large Titanite Shard",
  "Titanite Chunk",
  "Titanite Slab",
  "Petrified Dragon Bone",
  "Twinkling Titanite",
  "Dragon Bone",
  "Smooth & Silky Stone",
  "Cracked Red Eye Orb",
  "Blue Eye Orb",
  "Dragon Eye",
  "Aged Feather",
  "Homeward Bone",
  "Prism Stone",
  "Binoculars",
  "Repair Powder",
  "Pharros' Lockstone",
  "Torch",
  "Ladle",
  "Name-Engraved Ring",
  "Silvercat Ring",
  "Red Tearstone Ring",
  "Blue Tearstone Ring",
  "Sunlight Medal",
  "Dragon Scale",
  "Token of Fidelity",
  "Token of Spite",
  "Cracked Blue Eye Orb",
  "Soul Vessel",
  "Fireball",
  "Great Fireball",
  "Fire Orb",
  "Great Fire Orb",
  "Firestorm",
  "Chaos Storm",
  "Fire Whip",
  "Fire Tempest",
  "Combustion",
  "Great Combustion",
  "Fire Surge",
  "Fire Snake",
  "Fire Pillars",
  "Fireball of Wrath",
  "Flame Weapon",
  "Great Magic Weapon",
  "Magic Weapon",
  "Crystal Magic Weapon",
  "Dark Weapon",
  "Forbidden Sun",
  "Soul Arrow",
  "Great Soul Arrow",
  "Heavy Soul Arrow",
  "Homing Soulmass",
  "Soul Spear",
  "Crystal Soul Spear",
  "Soul Greatsword",
  "Soul Geyser",
  "Soul Vortex",
  "White Dragon Breath",
  "Dark Orb",
  "Dark Hail",
  "Darkstorm",
  "Affnity",
  "Homeward",
  "Heal",
  "Great Heal",
  "Soothing Sunlight",
  "Replenishment",
  "Refresh",
  "Chameleon",
  "Spook",
  "Hidden Weapon",
  "Resist Curse",
  "Power Within",
  "Carthus Beacon",
  "Force",
  "Wrath of the Gods",
  "Emit Force",
  "Sacred Oath",
  "Sacred Flame",
  "Sacred Storm",
  "Sunlight Spear",
  "Sunlight Blade",
  "Sunlight Weapon",
  "Replenishment Miracle",
  "Repair",
  "Great Repair",
  "Dark Edge",
  "Dark Blade",
  "Scraps of the Old Iron King",
  "Old Sun Ring",
  "Vengarl's Helm",
  "Vengarl's Gauntlets",
  "Vengarl's Leggings",
  "Alva Helm",
  "Alva Gauntlets",
  "Alva Leggings",
  "Faraam Helm",
  "Faraam Gauntlets",
  "Faraam Leggings",
  "Ring of Steel Protection",
  "Ring of Resistance",
  "Ring of Restoration",
  "Ring of Life Protection",
  "Ring of Force",
  "Ring of the Sun's First Born",
  "Ring of the Evil Eye",
  "Ring of Avarice",
  "Ring of Sacrifice",
  "Ring of Embers",
  "Ring of Fog",
  "Ring of Soul Protection",
  "Ring of Horse's Horn",
  "Ring of Blight",
  "Ring of Magic",
  "Ring of the Dead",
  "Ring of Flame",
  "Ring of Poison",
  "Ring of Shadow",
  "Ring of Tears",
  "Ring of Healing",
  "Ring of Skill",
  "Ring of Wisdom",
  "Ring of Courage",
  "Ring of Blood",
  "Ring of Death",
  "Ring of the Sun",
  "Ring of Strength",
  "Ring of Dexterity",
  "Ring of Endurance",
  "Ring of Vitality",
  "Ring of Faith",
  "Ring of Intelligence",
  "Ring of Humanity",
  "Dragonrider Bow",
  "Black Bow of Pharis",
  "Composite Bow",
  "Short Bow",
  "Longbow",
  "Greatbow",
  "Black Bow of the Dragonriders",
  "Light Crossbow",
  "Heavy Crossbow",
  "Repeating Crossbow",
  "Twin Crossbows",
  "Soul Arrow Scroll",
  "Fireball Scroll",
  "Great Fireball Scroll",
  "Soul Spear Scroll",
  "Homeward Scroll",
  "Repair Powder Scroll",
  "Divine Blessing Scroll",
  "Poisonbite Stone",
  "Purple Moss Clump",
  "White Branch of Yore",
  "Soul of a Hero",
  "Soul of a Nameless Soldier",
  "Soul of a Venerable Dragon",
  "Soul of the Looking Glass Knight",
  "Soul of the Smelter Demon",
  "Soul of the Ancient Dragon",
  "Lion Mage Hood",
  "Lion Mage Gloves",
  "Lion Mage Boots",
  "Hexer Hood",
  "Hexer Gloves",
  "Hexer Boots",
  "Wanderer Coat",
  "Wanderer Gloves",
  "Wanderer Boots",
  "Drakekeeper Helm",
  "Drakekeeper Gauntlets",
  "Drakekeeper Leggings",
  "Havel Helm",
  "Havel Armor",
  "Havel Gauntlets",
  "Havel Leggings",
  "King's Helm",
  "King's Gauntlets",
  "King's Leggings",
  "Heide Helm",
  "Heide Armor",
  "Heide Gauntlets",
  "Heide Leggings",
];

let lista3 = [
  "Estus Flask",
  "Ashen Estus Flask",
  "Undead Bone Shard",
  "Estus Shard",
  "Homeward Bone",
  "Ember",
  "Divine Blessing",
  "Hidden Blessing",
  "Seed of a Giant Tree",
  "Rubbish",
  "Titanite Shard",
  "Large Titanite Shard",
  "Titanite Chunk",
  "Titanite Slab",
  "Twinkling Titanite",
  "Titanite Scale",
  "Raw Gem",
  "Fire Gem",
  "Refined Gem",
  "Heavy Gem",
  "Sharp Gem",
  "Crystal Gem",
  "Dark Gem",
  "Chaos Gem",
  "Blessed Gem",
  "Lightning Gem",
  "Simple Gem",
  "Hollow Gem",
  "Blood Gem",
  "Poison Gem",
  "Prism Stone",
  "Rope Firebomb",
  "Black Firebomb",
  "Alluring Skull",
  "Repair Powder",
  "Charcoal Pine Resin",
  "Gold Pine Resin",
  "Human Pine Resin",
  "Carthus Rouge",
  "Rotten Pine Resin",
  "Bundle of Firebombs",
  "Duel Charm",
  "Undead Hunter Charm",
  "Rope Black Firebomb",
  "Green Blossom",
  "Bloodred Moss Clump",
  "Purple Moss Clump",
  "Blooming Purple Moss Clump",
  "Repair Powder",
  "Dung Pie",
  "Lloyd's Sword Ring",
  "Lloyd's Shield Ring",
  "Ring of Favor",
  "Havel's Ring",
  "Chloranthy Ring",
  "Ring of Steel Protection",
  "Ring of Sacrifice",
  "Life Ring",
  "Blue Tearstone Ring",
  "Red Tearstone Ring",
  "Hornet Ring",
  "Leo Ring",
  "Wolf Ring",
  "Carthus Milkring",
  "Carthus Bloodring",
  "Knight Slayer's Ring",
  "Knight's Ring",
  "Hunter's Ring",
  "Scholar Ring",
  "Priestess Ring",
  "Magic Clutch Ring",
  "Lightning Clutch Ring",
  "Fire Clutch Ring",
  "Dark Clutch Ring",
  "Covetous Silver Serpent Ring",
  "Covetous Gold Serpent Ring",
  "Sun Princess Ring",
  "Aldrich's Ruby",
  "Aldrich's Sapphire",
  "Pontiff's Right Eye",
  "Pontiff's Left Eye",
  "Prisoner's Chain",
  "Ring of the Sun's First Born",
  "Darkmoon Ring",
  "Ring of Favor +3",
  "Havel's Ring +3",
  "Chloranthy Ring +3",
  "Hornet Ring +3",
  "Ring of Steel Protection +3",
  "Life Ring +3",
  "Silvercat Ring",
  "Slumbering Dragoncrest Ring",
  "Lingering Dragoncrest Ring",
  "Bellowing Dragoncrest Ring",
  "Sage Ring",
  "Deep Ring",
  "Darkmoon Blade",
  "Sunlight Blade",
  "Sacred Oath",
  "Tears of Denial",
  "Heal Aid",
  "Great Heal",
  "Lightning Spear",
  "Great Lightning Spear",
  "Sunlight Spear",
  "Wrath of the Gods",
  "Deep Protection",
  "Magic Weapon",
  "Great Magic Weapon",
  "Crystal Magic Weapon",
  "Soul Arrow",
  "Great Soul Arrow",
  "Heavy Soul Arrow",
  "Great Heavy Soul Arrow",
  "Farron Dart",
  "Farron Hail",
  "Soul Greatsword",
  "Soul Spear",
  "Crystal Soul Spear",
  "Homing Soulmass",
  "Crystal Hail",
  "Affinity",
  "Dark Edge",
  "Dark Blade",
  "Deep Soul",
  "Great Deep Soul",
  "Great Chaos Fire Orb",
  "Chaos Bed Vestiges",
  "Fireball",
  "Great Fireball",
  "Fire Orb",
  "Sacred Flame",
  "Carthus Flame Arc",
  "Flash Sweat",
  "Iron Flesh",
  "Profaned Flame",
  "Boulder Heave",
  "Floating Chaos",
  "Rapier",
  "Longsword",
  "Broadsword",
  "Astora Straight Sword",
  "Lothric Knight Sword",
  "Dark Sword",
  "Irithyll Straight Sword",
  "Anri's Straight Sword",
  "Sunlight Straight Sword",
  "Claymore",
  "Zweihander",
  "Greatsword",
  "Black Knight Sword",
  "Farron Greatsword",
  "Lothric Knight Greatsword",
  "Cathedral Knight Greatsword",
  "Exile Greatsword",
  "Executioner's Greatsword",
  "Moonlight Greatsword",
  "Fume Ultra Greatsword",
  "Dragonslayer Greataxe",
  "Great Club",
  "Smough's Great Hammer",
  "Vordt's Great Hammer",
  "Yhorm's Great Machete",
  "Dragon Slayer Spear",
  "Spear",
  "Partizan",
  "Winged Spear",
  "Lothric Knight Long Spear",
  "Dragonslayer Spear",
  "Gargoyle Flame Spear",
  "Greatlance",
  "Halberd",
  "Lucerne",
  "Glaive",
  "Crescent Axe",
  "Black Knight Glaive",
  "Pontiff Knight Great Scythe",
  "Scythe",
  "Corvian Great Scythe",
  "Great Corvian Scythe",
  "Caestus",
  "Demon's Fist",
  "Dark Hand",
  "Drang Hammers",
  "Mace",
  "Morning Star",
  "Club",
  "Great Mace",
  "Dragon Tooth",
  "Farron Hammer",
  "Dragon Slayer Axe",
  "Battle Axe",
  "Hand Axe",
  "Greataxe",
  "Butcher Knife",
  "Black Knight Greataxe",
  "Brigand Axe",
  "Crow Quills",
  "Corvian Greatknife",
  "Bandit's Knife",
  "Dagger",
  "Mail Breaker",
  "Parrying Dagger",
  "Aquamarine Dagger",
  "Gotthard Twinswords",
  "Washing Pole",
  "Uchigatana",
  "Black Blade",
  "Chaos Blade",
  "Carthus Curved Sword",
  "Falchion",
  "Scimitar",
  "Pontiff Knight Curved Sword",
  "Storm Curved Sword",
  "Carthus Shotel",
  "Harpe",
  "Murakumo",
  "Carthus Curved Greatsword",
  "Exile Greatsword",
  "Pontiff Knight Great Scythe",
  "Wolf Knight's Greatsword",
  "Lorian's Greatsword",
  "Hollowslayer Greatsword",
  "Dragonslayer Great Axe",
  "Soul of Cinder Set",
  "Faraam Set",
  "Firelink Set",
  "Elite Knight Set",
  "Lothric Knight Set",
  "Knight Set",
  "Cathedral Knight Set",
  "Black Knight Set",
  "Silver Knight Set",
  "Winged Knight Set",
  "Fallen Knight Set",
  "Undead Legion Set",
  "Alva Set",
  "Sunless Set",
  "Maiden Set",
  "Sellsword Set",
  "Sorcerer Set",
  "Cleric Set",
  "Pyromancer Set",
  "Assassin Set",
  "Thief Set",
  "Herald Set",
  "Deacon Set",
  "Pontiff Knight Set",
  "Drang Set",
  "Executioner Set",
  "Shadow Set",
  "Dancer Set",
  "Dragonslayer Set",
  "Nameless King Set",
  "Smough's Set",
  "Fire Keeper Set",
  "Cornyx's Set",
  "Orbeck's Set",
  "Karla's Set",
  "Irina's Set",
  "Anri's Set",
  "Catarina Set",
  "Leonhard'  s Set",
  "Lapp's Set",
  "Harald Legion Set",
  "Desert Pyromancer Set",
  "Slave Knight Set",
  "Ringed Knight Set",
  "Black Witch Set",
  "Blindfold Mask",
  "Antiquated Plain Garb",
  "Antiquated Skirt",
  "Brass Set",
  "Wolf Knight Set",
  "Crown of Dusk",
  "Hollow Soldier Helm",
  "Executioner Helm",
  "Sunlight Shield",
  "Greatshield of Glory",
  "Lothric Knight Shield",
  "Cathedral Knight Greatshield",
  "Black Knight Shield",
  "Dragonslayer Greatshield",
  "Ancient Dragon Greatshield",
  "Moaning Shield",
  "Shield of Want",
  "Grass Crest Shield",
  "Spirit Tree Crest Shield",
  "Golden Falcon Shield",
  "Silver Eagle Kite Shield",
  "Kite Shield",
  "Caduceus Round Shield",
  "Round Shield",
  "Target Shield",
  "Small Leather Shield",
  "Buckler",
  "Parrying Shield",
  "East-West Shield",
  "Key to the Embedded",
  "Small Lothric Banner",
  "Dull Ember",
  "Dungeon Cell Key",
  "Grand Archives Key",
  "Tower Key",
  "Lift Chamber Key",
  "Jailbreaker's Key",
  "Contraption Key",
  "Cage Key",
  "Small Doll",
  "Old Cell Key",
  "Path of the Dragon Emote",
  "Dragon Head Stone",
  "Dragon Torso Stone",
  "Dragon Head Greatstone",
  "Dragon Torso Greatstone",
  "Soul of Cinder",
  "Soul of the Nameless King",
  "Soul of the Twin Princes",
  "Soul of Aldrich",
  "Soul of Yhorm the Giant",
  "Soul of the Dancer",
  "Soul of the Lords",
  "Soul of Sister Friede",
  "Soul of the Demon Prince",
  "Soul of Darkeater Midir",
  "Soul of Slave Knight Gael",
];

let lista4 = [
  "Dagger",
  "Great Epee",
  "Club",
  "Halberd",
  "Parrying Dagger",
  "Queelign's Greatsword",
  "Curved Club",
  "Banished Knight's Halberd",
  "Misericorde",
  "Godskin Stitcher",
  "Spiked Club",
  "Lucerne",
  "Great Knife",
  "Bloody Helice",
  "Stone Club",
  "Glaive",
  "Bloodstained Dagger",
  "Dragon King's Cragblade",
  "Mace",
  "Vulgar Militia Shotel",
  "Erdsteel Dagger",
  "Sword Lance",
  "Morning Star",
  "Vulgar Militia Saw",
  "Fire Knight's Shortsword",
  "Warpick",
  "Guardian's Swordspear",
  "Wakizashi",
  "Scimitar",
  "Monk's Flamemace",
  "Gargoyle's Halberd",
  "Main-gauche",
  "Falchion",
  "Varre's Bouquet",
  "Nightrider Glaive",
  "Celebrant's Sickle",
  "Shamshir",
  "Envoy's Horn",
  "Pest's Glaive",
  "Ivory Sickle",
  "Grossmesser",
  "Nox Flowing Hammer",
  "Ripple Crescent Halberd",
  "Crystal Knife",
  "Bandit's Curved Sword",
  "Ringed Finger",
  "Golden Halberd",
  "Scorpion's Stinger",
  "Shotel",
  "Scepter of the All-Knowing",
  "Dragon Halberd",
  "Cinquedea",
  "Scavenger's Curved Sword",
  "Flowerstone Gavel",
  "Loretta's War Sickle",
  "Glintstone Kris",
  "Mantis Blade",
  "Marika's Hammer",
  "Commander's Standard",
  "Reduvia",
  "Beastman's Curved Sword",
  "Spirit Glaive",
  "Black Knife",
  "Flowing Curved Sword",
  "Flail",
  "Serpent-God's Curved Sword",
  "Flail",
  "Throwing Blades",
  "Magma Blade",
  "Nightrider Flail",
  "Reapers",
  "Smithscript Dagger",
  "Spirit Sword",
  "Chainlink Flail",
  "Family Heads",
  "Grave Scythe",
  "Wing of Astel",
  "Serpent Flail",
  "Halo Scythe",
  "Falx",
  "Bastard's Stars",
  "Winged Scythe",
  "Obsidian Lamina",
  "Dancing Blade of Ranah",
  "Horned Warrior's Sword",
  "Great Hammers",
  "Large Club",
  "Curved Great Club",
  "Whip",
  "Whip",
  "Urumi",
  "Hoslow's Petal Whip",
  "Tooth Whip",
  "Magma Whip Candlestick",
  "Giant's Red Braid",
  "Fists",
  "Caestus",
  "Spiked Caestus",
  "Katar",
  "Pata",
  "Iron Ball",
  "Star Fist",
  "Clinging Bone",
  "Veteran's Prosthesis",
  "Cipher Pata",
  "Poisoned Hand",
  "Madding Hand",
  "Golem Fist",
  "Thiollier's Hidden Needle",
  "Grafted Dragon",
  "Dryleaf Arts",
  "Dane's Footwork",
  "Staff of the Avatar",
  "Rotten Staff",
  "Claws",
  "Envoy's Greathorn",
  "Hookclaws",
  "Bloodhound Claws",
  "Venomous Fang",
  "Raptor Talons",
  "Claws of Night",
  "Axe of Godfrey",
  "Beast Claws",
  "Beast Claw",
  "Red Bear's Claw",
  "Perfume Bottles",
  "Firespark",
  "Lightning",
  "Chilling",
  "Frenzyflame",
  "Deadly Poison",
  "Cross-Naginata",
  "Clayman's Harpoon",
  "Bloodfiend's Fork",
  "Celebrant's Rib-Rake",
  "Torchpole",
  "Smithscript Spear",
  "Inquisitor's Girandole",
  "Crystal Spear",
  "Rotten Crystal Spear",
  "Cleanrot Spear",
  "Death Ritual Spear",
  "Bolt of Gransax",
  "Great Spears",
  "Lance",
  "Messmer Soldier's Spear",
  "Treespear",
  "Serpent-Hunter",
  "Vyke's War Spear",
  "Barbed Staff-Spear",
  "Bloodfiend's Sacred Spear",
  "Mohgwyn's Sacred Spear",
  "Spear of the Impaler",
  "Great Omenkiller Cleaver",
  "Rusted Anchor",
  "Butchering Knife",
  "Bonny Butchering Knife",
  "Gargoyle's Great Axe",
  "Gargoyle's Black Axe",
  "Death Knight's Longhaft Axe",
  "Winged Greathorn",
  "Axe of Godrick",
  "Putrescence Cleaver",
  "Knight set",
  "Vagabond Knight set",
  "Carian Knight set",
  "Godrick Knight set",
  "Cuckoo Knight set",
  "Redmane Knight set",
  "Gelmir Knight set",
  "Leyndell Knight set",
  "Haligtree Knight set",
  "Mausoleum Knight set",
  "Black Knight set",
  "Bloodhound Knight set",
  "Cleanrot set",
  "Fire Knight set",
  "Death Knight set",
  "Divine Bird Warrior set",
  "Horned Warrior set",
  "Divine Beast set",
  "Oathseeker set",
  "Raging Wolf set",
  "Hoslow's set",
  "Twinned set",
  "Drake Knight set",
  "Blaidd's set",
  "Briar set",
  "Fingerprint set",
  "Rakshasa set",
  "Royal Remains set",
  "All-Knowing set",
  "Royal Knight set",
  "Rellana's set",
  "Maliketh's set",
  "Banished Knight set",
  "Night's Cavalry set",
  "Solitude set",
  "Veteran's set",
  "Scaled set",
  "Beast Champion set",
  "Tree Sentinel set",
  "Malformed Dragon set",
  "Crucible Axe set",
  "Crucible Tree set",
  "Gaius's set",
  "General Radahn's set",
  "Young Lion's set",
  "Lionel's set",
  "Bull-Goat set",
  "Verdigris set",
  "Omen set",
  "Fire Prelate set",
  "Guilty set",
  "Traveler's set",
  "Commoner's set",
  "Aristocrat set",
  "Soldier Noble set",
  "Old Aristocrat set",
  "Page set",
  "High Page set",
  "Guardian set",
  "Festive set",
  "Blue Festive set",
  "Prisoner set",
  "Hornsent set",
  "Bloodsoaked set",
  "Mushroom set",
  "Leather set",
  "Blue Cloth set",
  "Noble set",
  "Nomadic Merchant set",
  "Bandit set",
  "Confessor set",
  "War Surgeon set",
  "Thiollier's set",
  "Omenkiller set",
  "Raptor's set",
  "Gravebird set",
  "Dancer's set",
  "Raya Lucarian Foot Soldier set",
  "Leyndell Foot Soldier set",
  "Godrick Foot Soldier set",
  "Haligtree Foot Soldier set",
  "Radahn Foot Soldier set",
  "Mausoleum Foot Soldier set",
  "Highwayman set",
  "Common Soldier set",
  "Vulgar Militia set",
  "Shadow Militia set",
  "Duelist set",
  "Rotten Duelist set",
  "Nox Monk set",
  "Nox Swordstress set",
  "Night Maiden set",
  "Champion set",
  "Highland set",
  "Gloried set",
  "Iron Rivet set",
  "Igon's set",
  "Ascetic's set",
  "Dryleaf set",
  "Goldmask's set",
  "Chain set",
  "Godrick Soldier set",
  "Raya Lucarian Soldier set",
  "Radahn Soldier set",
  "Leyndell Soldier set",
  "Haligtree Soldier set",
  "Mausoleum Soldier set",
  "Messmer Soldier set",
  "Shaman set",
  "Iron set",
  "Exile set",
  "Kaiden set",
  "Land of Reeds set",
  "White Reed set",
  "Ronin's set",
  "Eccentric set",
  "Freyja's set",
  "Marionette set",
  "Blue Silver set",
  "Fire Monk set",
  "Blackflame Monk set",
  "Black Knife set",
  "Night set",
  "Zamor set",
  "Malenia's set",
  "Elden Lord set",
  "Messmer's set",
  "Astrologer set",
  "Juvenile Scholar set",
  "Raya Lucarian Sorcerer set",
  "Lazuli Sorcerer set",
  "Battlemage set",
  "Errant Sorcerer set",
  "Spellblade set",
  "Alberich's set",
  "Preceptor's set",
  "Azur's Glintstone set",
  "Lusat's Glintstone set",
  "Queen of the Full Moon set",
  "Snow Witch set",
  "High Priest set",
  "Fia's set",
  "Prophet set",
  "Traveling Maiden set",
  "Finger Maiden set",
  "Sage set",
  "Perfumer set",
  "Perfumer Traveler set",
  "Depraved Perfumer set",
  "Ruler's set",
  "Consort set",
  "House Marais set",
  "Fur set",
  "Godskin Apostle set",
  "Godskin Noble set",
  "Sanguine Noble set",
  "Ansbach's set",
  "Blackguard's Iron Mask",
  "Commoner's Simple Garb",
  "Black Dumpling",
  "Guardian Garb (Full Bloom)",
  "Mushroom Crown",
  "Deathbed Dress",
  "St. Trina's Blossom",
  "Corhyn's Robe",
  "Circlet of Light",
  "Upper-Class Robe",
  "Karalos Glintstone Crown",
  "Fell Omen Cloak",
  "Olivinus Glintstone Crown",
  "Lord of Blood's Robe",
  "Twinsage Glintstone Crown",
  "Gravebird's Blackquill Armour",
  "Witch's Glintstone Crown",
  "Tree Surcoat",
  "Mask of Confidence",
  "Eye Surcoat",
  "Greathood",
  "Dirty Chainmail",
  "Crimson Tear Scarab",
  "Leda's Armor",
  "Cerulean Tear Scarab",
  "Ash-of-War Scarab",
  "Glintstone Scarab",
  "Incantation Scarab",
  "Imp Head (Cat)",
  "Imp Head (Wolf)",
  "Imp Head (Corpse)",
  "Imp head (Long-Tongued)",
  "Imp Head (Elder)",
  "Imp Head (Lion)",
  "Imp Head (Fanged)",
  "Nox Mirrorhelm",
  "Iji's Mirrorhelm",
  "Silver Tear Mask",
  "Envoy Crown",
  "Octopus Head",
  "Jar",
  "Greatjar",
  "Albinauric Mask",
  "Crimson Hood",
  "Pelt of Ralva",
  "Marionette Soldier Birdhelm",
  "Greathelm",
  "Winged Serpent Helm",
  "Deathmask Helm",
  "Salza's Hood",
  "Diallos's Mask",
  "Crucible Hammer Helm",
  "Pumpkin Helm",
  "Divine Beast Head",
  "Commoner's Simple Garb",
  "Guardian Garb (Full Bloom)",
  "Deathbed Dress",
  "Corhyn's Robe",
  "Upper-Class Robe",
  "Fell Omen Cloak",
  "Lord of Blood's Robe",
  "Gravebird's Blackquill Armour",
  "Tree Surcoat",
  "Eye Surcoat",
  "Finger Seal",
  "Erdtree Seal",
  "Golden Order Seal",
  "Dryleaf Seal",
  "Fire Knight's Seal",
  "Spiraltree Seal",
  "Gravel Stone Seal",
  "Giant's Seal",
  "Godslayer's Seal",
  "Clawmark Seal",
  "Frenzied Flame Seal",
  "Dragon Communion Seal",
  "Hand Ballista",
  "Jar Cannon",
  "Rabbath's Cannon",
  "Astrologer's Staff",
  "Glintstone Staff",
  "Academy Glintstone Staff",
  "Digger's Staff",
  "Demi-Human Queen's Staff",
  "Azur's Glintstone Staff",
  "Lusat's Glintstone Staff",
  "Carian Glintstone Staff",
  "Carian Glintblade Staff",
  "Carian Regal Scepter",
  "Albinauric Staff",
  "Staff of Loss",
  "Gelmir Glintstone Staff",
  "Crystal Staff",
  "Rotten Crystal Staff",
  "Meteorite Staff",
  "Staff of the Guilty",
  "Prince of Death's Staff",
  "Maternal Staff",
  "Staff of the Great Beyond",
  "Shortbow",
  "Composite Bow",
  "Red Branch Shortbow",
  "Misbegotten Shortbow",
  "Harp Bow",
  "Bone Bow",
  "Longbow",
  "Albinauric Bow",
  "Black Bow",
  "Ansbach's Longbow",
  "Pulley Bow",
  "Horn Bow",
  "Serpent Bow",
  "Erdtree Bow",
  "Greatbow",
  "Golem Greatbow",
  "Erdtree Greatbow",
  "Igon's Greatbow",
  "Lion Greatbow",
  "Soldier's Crowwsbow",
  "Light Crossbow",
  "Heavy Crossbow",
  "Arbalest",
  "Crepus's Black-Key Crossbow",
  "Pulley Crossbow",
  "Repeating Crossbow",
  "Spread Crossbow",
  "Full Moon Crossbow",
  "Torch",
  "Beast-Repellent Torch",
  "Steel-Wire Torch",
  "Sentry's Torch",
  "Ghostflame Torch",
  "St Trina's Torch",
  "Nanaya's Torch",
  "Lamenting Visage",
  "Rickety Shield",
  "Riveted Wooden Shield",
  "Blue-White Wooden Shield",
  "Scripture Wooden Shield",
  "Red Thorn Roundshield",
  "Pillory Shield",
  "Buckler",
  "Iron Roundshield",
  "Gilded Iron Shield",
  "Man-Serpent's Shield",
  "Ice Crest Shield",
  "Rift Shield",
  "Perfumer's Shield",
  "Shield of the Guilty",
  "Spiralhorn Shield",
  "Smoldering Shield",
  "Coil Shield",
  "Smithscript Shield",
  "Shield of Night",
  "Hawk Crest Wooden Shield",
  "Horse Crest Wooden Shield",
  "Candletree Wooden Shield",
  "Flame Crest Wooden Shield",
  "Marred Wooden Shield",
  "Sun Realm Shield",
  "Round Shield",
  "Large Leather Shield",
  "Black Leather Shield",
  "Marred Leather Shield",
  "Heater Shield",
  "Blue Crest Heater Shield",
  "Red Crest Heater Shield",
  "Beast Crest Heater Shield",
  "Inverted Hawk Heater Shield",
  "Eclipse Crest Heater Shield",
  "Kite Shield",
  "Blue-Gold Kite Shield",
  "Scorpion Kite Shield",
  "Twinbird Kite Shield",
  "Brass Shield",
  "Messmer Soldier Shield",
  "Banished Knight's Shield",
  "Wolf Crest Shield",
  "Serpent Crest Shield",
  "Albinauric Shield",
  "Beastman's Jar-Shield",
  "Carian Knight's Shield",
  "Silver Mirrorshield",
  "Great Turtle Shield",
  "Golden Lion Shield",
  "Wooden Greatshield",
  "Lordsworn's Shield",
  "Briar Greatshield",
  "Spiked Palisade Shield",
  "Icon Shield",
  "Golden Beast Crest Shield",
  "Manor Towershield",
  "Crossed-Tree Towershield",
  "Inverted Hawk Towershield",
  "Dragon Towershield",
  "Distinguished Greatshield",
  "Gilded Greatshield",
  "Cuckoo Greatshield",
  "Redmane Greatshield",
  "Golden Greatshield",
  "Haligtree Crest Greatshield",
  "Black Steel Greatshield",
  "Crucible Hornshield",
  "Dragonclaw Shield",
  "Fingerprint Stone Shield",
  "Eclipse Crest Greatshield",
  "Ant's Skull Plate",
  "Erdtree Greatshield",
  "Jellyfish Shield",
  "Visage Shield",
  "One-Eyed Shield",
  "Verdigris Greatshield",
  "Dueling Shield",
  "Carian Thrusting Shield",
  "Crimson Amber Medallion",
  "Crimson Seed Talisman",
  "Blessed Dew Talisman",
  "Cerulean Amber Medallion",
  "Cerulean Seed Talisman",
  "Blessed Blue Dew Talisman",
  "Talisman of Lord's Bestowal",
  "Viridian Amber Medallion",
  "Green Turtle Talisman",
  "Two-Headed Turtle Talisman",
  "Arsenal Charm",
  "Great-Jar's Arsenal",
  "Erdtree's Favour",
  "Radagon's Scarseal",
  "Radagon's Soreseal",
  "Marika's Soreseal",
  "Marika's Scarseal",
  "Starscourge Heirloom",
  "Prosthesis-Wearer Heirloom",
  "Stargazer Heirloom",
  "Two Fingers Heirloom",
  "Outer God Heirloom",
  "Dragoncrest Shield Talisman",
  "Dragoncrest Greatshield Talisman",
  "Spelldrake Talisman",
  "Flamedrake Talisman",
  "Boltdrake Talisman",
  "Haligdrake Talisman",
  "Golden Braid",
  "Pearldrake Talisman",
  "Immunizing Horn Charm",
  "Stalwart Horn Charm",
  "Clarifying Horn Charm",
  "Mottled Necklace",
  "Prince of Death's Pustule",
  "Prince of Death's Cyst",
  "Ailment Talisman",
  "Dagger Talisman",
  "Curved Sword Talisman",
  "Twinblade Talisman",
  "Axe Talisman",
  "Hammer Talisman",
  "Spear Talisman",
  "Lance Talisman",
  "Claw Talisman",
  "Two-Handed Sword Talisman",
  "Greatshield Talisman",
  "Pearl Shield Talisman",
  "Retaliatory Crossed-Tree",
  "Lacerating Crossed-Tree",
  "Arrow's Sting Talisman",
  "Arrow's Reach Talisman",
  "Arrow's Soaring Sting Talisman",
  "Sharpshot Talisman",
  "Graven-School Talisman",
  "Graven-Mass Talisman",
  "Fathful Canvas Talisman",
  "Flock's Canvas Talisman",
  "Primal Glinstone Blade",
  "Moon of Nokstella",
  "Old Lord's Talisman",
  "Radagon Icon",
  "Beloved Stardust",
  "Roar Medallion",
  "Companion Jar",
  "Perfumer's Talisman",
  "Carian Filigreed Crest",
  "Warrior Jar Shard",
  "Shard of Alexander",
  "Godfrey Icon",
  "Rellana's Cameo",
  "Shattered Stone Talisman",
  "Smithing Talisman",
  "Enraged Divine Beast",
  "Talisman of the Dread",
  "Bull-Goat's Talisman",
  "Blue Dancer Charm",
  "Verdigris Discus",
  "Fire Scorpion Charm",
  "Lightning Scorpion Charm",
  "Magic Scorpion Charm",
  "Sacred Scorpion Charm",
  "Crucible Scale Talisman",
  "Crucible Feather Talisman",
  "Crucible Knot Talisman",
  "Fine Crucible Feather",
  "Talisman of all Crucibles",
  "Red-Feathered Branchsword",
  "Blue-Feathered Branchsword",
  "Ritual Sword Talisman",
  "Ritual Shield Talisman",
  "Assassin's Crimson Dagger",
  "Assassin's Cerulean Dagger",
  "Winged Sword Insignia",
  "Rotten Winged Sword Insignia",
  "Millicent's Prosthesis",
  "Godskin Swadlling Cloth",
  "Kindred of Rot's Exultation",
  "Lord of Blood's Exultation",
  "Aged One's Exultation",
  "St Trina's Smile",
  "Blade of Mercy",
  "Taker's Cameo",
  "Ancestral Spirit's Horn",
  "Crusade Insignia",
  "Dried Bouquet",
  "Gold Scarab",
  "Silver Scarab",
  "Crepus's Vial",
  "Concealing Veil",
  "Longtail Cat Talisman",
  "Furled Finger's Trick-Mirror",
  "Host's Trick-Mirror",
  "Shabriri's Woe",
  "Daedicar's Woe",
  "Sacrificial Twig",
  "Stamp (Upward Cut)",
  "Stamp (Sweep)",
  "Wild Strikes",
  "Lion's Claw",
  "Savage Lion's Claw",
  "Cragblade",
  "Kick",
  "Endure",
  "Ground Slam",
  "Earthshaker",
  "Hoarah Loux's Earthshaker",
  "War Cry",
  "Barbaric Roar",
  "Braggart's Roar",
  "Troll's Roar",
  "Spinning Slash",
  "Impaling Thrust",
  "Blind Spot",
  "Swift Slash",
  "Piercing Fang",
  "Repeating Thrust",
  "Double Slash",
  "Sword Dance",
  "Unsheathe",
  "Overhead Stance",
  "Quickstep",
  "Bloodhound Step",
  "Raptor of the Mists",
  "Beast's Roar",
  "Savage Claws",
  "Raging Beast",
  "Piercing Throw",
  "Scattershot Throw",
  "Square Off",
  "Wing Stance",
  "Charge Forth",
  "Giant Hunt",
  "Storm Blade",
  "Storm Assault",
  "Stormcaller",
  "Storm Stomp",
  "Vacuum Slice",
  "Phantom Slash",
  "Determination",
  "Royal Knight's Resolve",
  "Spinning Strikes",
  "Glintstone Pebble",
  "Glintblade Phalanx",
  "Carian Greatsword",
  "Carian Grandeur",
  "Carian Sovereignty",
  "Spinning Weapon",
  "Loretta's Slash",
  "Gravitas",
  "Spinning Gravity Thrust",
  "Waves of Darkness",
  "Flaming Strike",
  "Flame of the Redmanes",
  "Eruption",
  "Prelate's Charge",
  "Black Flame Tornado",
  "Flame Skewer",
  "Flame Spear",
  "Thunderbolt",
  "Lightning Slash",
  "Blinkbolt",
  "Lightning Ram",
  "Sacred Blade",
  "Prayerful Strike",
  "Sacred Ring of Light",
  "Sacred Order",
  "Shared Order",
  "Golden Land",
  "Golden Slam",
  "Golden Vow",
  "Vow of the Indomitable",
  "Holy Ground",
  "Aspects of the Crucible: Wings",
  "Poisonous Mist",
  "Poison Moth Flight",
  "The Poison Flower Blooms Twice",
  "Blood Blade",
  "Bloody Slash",
  "Blood Tax",
  "Seppuku",
  "Ice Spear",
  "Chilling Mist",
  "Ghostflame Call",
  "Hoarfrost Stomp",
  "Divine Beast Frost Stomp",
  "Spectral Lance",
  "Lifesteal Fist",
  "White Shadow's Lure",
  "Assassin's Gambit",
  "Shriek of Sorrow",
  "Palm Blast",
  "Dryleaf Whirlwind",
  "Wall of Sparks",
  "Rolling Sparks",
  "Mighty Shot",
  "Through and Through",
  "Igon's Drake Hunt",
  "Barrage",
  "Sky Shot",
  "Enchanted Shot",
  "Rain of Arrows",
  "Parry",
  "Golden Parry",
  "Storm Wall",
  "Shield Bash",
  "Shield Crash",
  "Barricade Shield",
  "Thops's Barrier",
  "Carian Retaliation",
  "Shield Strike",
  "No Skill",
  "Wandering Noble",
  "Noble Sorcerer",
  "Nomad",
  "Putrid Corpse",
  "Skeletal Militiaman",
  "Skeletal Bandit",
  "Albinauric",
  "Winged Misbegotten",
  "Demi-Human",
  "Clayman",
  "Oracle Envoy",
  "Man-Fly",
  "Lone Wolf",
  "Rotten Stray",
  "Giant Rat",
  "Warhawk",
  "Land Squirt",
  "Spirit Jellyfish",
  "Miranda Sprout",
  "Spider Scorpion",
  "Fingercreeper",
  "Fanged Imp",
  "Bigmouth Imp",
  "Gravebird",
  "Soldjars of Fortune",
  "Archer",
  "Greatshield Soldier",
  "Page",
  "Vulgar Militia",
  "Marionette Soldier",
  "Avionette Soldier",
  "Kaiden Sellsword",
  "Mad Pumpkin Head",
  "Fire Monk",
  "Ancestral Follower",
  "Horned Warrior",
  "Azula Beastman",
  "Man-Serpent",
  "Crystalian",
  "Kindred of Rot",
  "Bloodfiend Hexer",
  "Glintstone Sorcerer",
  "Twinsage Sorcerer",
  "Inquisitor",
  "Godrick Soldier",
  "Raya Lucaria Soldier",
  "Leyndell Soldier",
  "Radahn Soldier",
  "Haligtree Soldier",
  "Mausoleum Soldier",
  "Messmer Soldier",
  "Stormhawk Deenh",
  "Banished Knight Oleg",
  "Banished Knight Engvall",
  "Bloodhound Knight Floh",
  "Black Knight Captain Huw",
  "Black Knight Commander Andreas",
  "Fire Knight Queelign",
  "Fire Knight Hilde",
  "Swordhand of Night Jolán",
  "Jolán and Anna",
  "Battlemage Hugues",
  "Latenna the Albinauric",
  "Perfumer Tricia",
  "Depraved Perfumer Carmaan",
  "Omenkiller Rollo",
  "Blackflame Monk Amon",
  "Curseblade Meera",
  "Demi-Human Swordsman Yosh",
  "Ancient Dragon Knight Kristoff",
  "Redmane Knight Ogha",
  "Lhutel the Headless",
  "Cleanrot Knight Finlay",
  "Black Knife Tiche",
  "Divine Bird Warrior Ornis",
  "Taylew the Golem Smith",
  "Ancient Dragon Florissax",
  "Mimic Tear",
  "Finger Maiden Therolina",
  "Jarwight",
  "Dolores the Sleeping Arrow",
  "Nightmaiden & Swordstress",
  "Nepheli Loux",
  "Dung Eater",
  "Glintstone Pebble",
  "Swift Glintstone Shard",
  "Great Glintstone Shard",
  "Glintstone Cometshard",
  "Comet",
  "Shard Spiral",
  "Glintstone Stars",
  "Star Shower",
  "Glintstone Arc",
  "Crystal Barrage",
  "Crystal Burst",
  "Cannon of Haima",
  "Gavel of Haima",
  "Shatter Earth",
  "Rock Blaster",
  "Scholar's Armament",
  "Scholar's Shield",
  "Starlight",
  "Terra Magica",
  "Thops's Barrier",
  "Comet Azur",
  "Stars of Ruin",
  "Founding Rain of Stars",
  "Magic Glintblade",
  "Glintblade Trio",
  "Glintblade Phalanx",
  "Carian Phalanx",
  "Greatblade Phalanx",
  "Magic Downpour",
  "Loretta's Greatbow",
  "Loretta's Mastery",
  "Rennala's Full Moon",
  "Ranni's Dark Moon",
  "Rellana's Twin Moons",
  "Carian Slicer",
  "Carian Greatsword",
  "Carian Piercer",
  "Adula's Moonblade",
  "Lucidity",
  "Carian Retaliation",
  "Miriam's Vanishing",
  "Ambush Shard",
  "Night Shard",
  "Night Comet",
  "Night Maiden's Mist",
  "Uneseen Blade",
  "Unseen Form",
  "Eternal Darkness",
  "Magma Shot",
  "Roiling Magma",
  "Gelmir's Fury",
  "Rykard's Rancor",
  "Glintstone Icecrag",
  "Freezing Mist",
  "Frozen Armament",
  "Zamor Ice Storm",
  "Shattering Crystal",
  "Crystal Torrent",
  "Crystal Release",
  "Gravity Well",
  "Collapsing Stars",
  "Gravitational Missile",
  "Rock Sling",
  "Blades of Stone",
  "Meteorite",
  "Meteorite of Astel",
  "Glintstone Nail",
  "Glintstone Nails",
  "Fleeting Microcosm",
  "Cherishing Fingers",
  "Oracle Bubbles",
  "Great Oracular Bubble",
  "Briars of Sin",
  "Briars of Punishment",
  "Mantle of Thorns",
  "Impenetrable Thorns",
  "Rancorcall",
  "Ancient Death Rancor",
  "Mass of Putrescence",
  "Explosive Ghostflame",
  "Rings of Spectral Light",
  "Fia's Mist",
  "Tibia's Summons",
  "Vortex of Putrescence",
  "Urgent Heal",
  "Heal",
  "Great Heal",
  "Lord's Heal",
  "Cure Poison",
  "Lord's Aid",
  "Magic Fortification",
  "Flame Fortification",
  "Lightning Fortification",
  "Divine Fortification",
  "Lord's Divine Fortification",
  "Rejection",
  "Shadow Bait",
  "Darkness",
  "Assassin's Approach",
  "Golden Vow",
  "Barrier of Gold",
  "Golden Lightning Fortification",
  "Protection of the Erdtree",
  "Wrath of Gold",
  "Wrath from Far",
  "Heal from Afar",
  "Erdtree Heal",
  "Blessing's Boon",
  "Blessing of the Erdtree",
  "Minor Erdtree",
  "Aspects of the Crucible: Breath",
  "Aspects of the Crucible: Horns",
  "Aspects of the Crucible: Tail",
  "Aspects of the Crucible: Thorns",
  "Aspects of the Crucible: Bloom",
  "Land of Shadow",
  "Elden Stars",
  "Black Blade",
  "Discus of Light",
  "Triple Rings of Light",
  "Radagon's Rings of Light",
  "Multilayered Ring of Light",
  "Litany of Proper Death",
  "Order Healing",
  "Order's Blade",
  "Immutable Shield",
  "Law of Causality",
  "Law of Regression",
  "Light of Miquella",
  "Lightning Spear",
  "Knight's Lightning Spear",
  "Lightning Strike",
  "Honed Bolt",
  "Ancient Dragon's Lightning Spear",
  "Ancient Dragon's Lightning Strike",
  "Lansseax's Glaive",
  "Fortissax's Lightning Spear",
  "Frozen Lightning Spear",
  "Death Lightning",
  "Electrify Armament",
  "Electrocharge",
  "Dragonbolt Blessing",
  "Vyke's Dragonbolt",
  "Dragonbolt of Florissax",
  "Golden Arcs",
  "Giant Golden Arc",
  "Spira",
  "Watchful Spirit",
  "Divine Bird Feathers",
  "Divine Beast Tornado",
  "Catch Flame",
  "O, Flame!",
  "Flame Sling",
  "Giantsflame Take Thee",
  "Flame, Fall Upon Them",
  "Flame of the Fell God",
  "Surge, O Flame!",
  "Whirl, O Flame!",
  "Burn, O Flame!",
  "Flame, Cleanse Me",
  "Flame, Protect Me",
  "Flame, Grant Me Strength",
  "Fire's Deadly Sin",
  "Fire Serpent",
  "Rain of Fire",
  "Messmer's Orb",
  "Black Flame",
  "Scouring Black Flame",
  "Black Flame Ritual",
  "Black Flame Blade",
  "Black Flame's Protection",
  "Noble Presence",
  "Beast Claw",
  "Gurranq's Beast Claw",
  "Bestial Sling",
  "Stone of Gurranq",
  "Bestial Constitution",
  "Bestial Vitality",
  "Roar of Rugalea",
  "Swarm of Flies",
  "Rotten Butterflies",
  "Bloodflame Talons",
  "Furious Blade of Ansbach",
  "Bloodboon",
  "Bloodflame Blade",
  "Poison Mist",
  "Poison Armament",
  "Pest Threads",
  "Pest-Thread Spears",
  "Scarlet Aeonia",
  "The Flame of Frenzy",
  "Midra's Flame of Frenzy",
  "Unendurable Frenzy",
  "Frenzied Burst",
  "Howl of Shabriri",
  "Inescapable Frenzy",
  "Dragonfire",
  "Agheel's Flame",
  "Magma Breath",
  "Theodorix's Magma",
  "Glintstone Breath",
  "Smarag's Glintstone Breath",
  "Rotten Breath",
  "Ekzykes's Decay",
  "Dragonice",
  "Borealis's Mist",
  "Ghostflame Breath",
  "Placidusax's Ruin",
  "Dragonclaw",
  "Dragonmaw",
  "Greyoll's Roar",
  "Bayle's Flame Lightning",
  "Bayle's Tyranny",
  "Crimson Crystal Tear (Left)",
  "Crimson Crystal Tear (Right)",
  "Crimsonspill Crystal Tear",
  "Crimsonburst Crystal Tear",
  "Crimsonburst Dried Tear",
  "Cerulean Crystal Tear (Left)",
  "Cerulean Crystal Tear (Right)",
  "Greenspill Crystal Tear",
  "Greenburst Crystal Tear",
  "Strength-Knot Crystal Tear",
  "Dexterity-Knot Crystal Tear",
  "Intelligence-Knot Crystal Tear",
  "Faith-Knot Crystal Tear",
  "Opaline Hardtear",
  "Speckled Hardtear",
  "Leaden Hardtear",
  "Deflecting Hardtear",
  "Magic-Shrouding Cracked Tear",
  "Flame-Shrouding Cracked Tear",
  "Lightning-Shrouding Cracked Tear",
  "Holy-Shrouding Cracked Tear",
  "Stonebarb Cracked Tear",
  "Spiked Cracked Tear",
  "Thorny Cracked Tear",
  "Crimson-Sapping Cracked Tear",
  "Cerulean-Sapping Cracked Tear",
  "Bloodsucking Cracked Tear",
  "Twiggy Cracked Tear",
  "Winged Crystal Tear",
  "Windy Crystal Tear",
  "Glovewort Crystal Tear",
  "Crimson Bubbletear",
  "Crimsonwhorl Bubbletear",
  "Opaline Bubbletear",
  "Cerulean Hidden Tear",
  "Viridian Hidden Tear",
  "Purifying Crystal Tear",
  "Ruptured Crystal Tear (Left)",
  "Ruptured Crystal Tear (Right)",
  "Oil-Soaked Tear",
  "Wraith Calling Bell",
  "Ancestral Infant's Head",
  "Omen Bairn",
  "Regal Omen Bairn",
  "Horned Bairn",
  "Perfumed Oil of Ranah",
  "Bondstone",
  "Mimic's Veil",
  "Margit's Shackle",
  "Mohg's Shackle",
  "Blasphemous Claw",
  "Lantern",
  "Telescope",
  'Prattling Pate "Hello"',
  'Prattling Pate "Thank You"',
  'Prattling Pate "Apologies"',
  'Prattling Pate "Wonderful"',
  'Prattling Pate "Please Help"',
  'Prattling Pate "My Beloved"',
  'Prattling Pate "Let\'s Get To It"',
  'Prattling Pate "You\'re Beautiful"',
  'Prattling Pate "Lamentation"',
  "Rock Heart",
  "Priestess Heart",
  "Lamenter's Mask",
  "Spirit Calling Bell",
  "Crafting Kit",
  "Whetstone Knife",
  "Glintstone Whetblade",
  "Iron Whetblade",
  "Red-Hot Whetblade",
  "Black Whetblade",
  "Sanctified Whetblade",
  "Tailoring Tools",
  "Golden Tailoring Tools",
  "Point Forwards",
  "Point Upwards",
  "Point Downwards",
  "Wait!",
  "Calm Down!",
  "Wave",
  "Beckon",
  "Casual Greeting",
  "Warm Welcome",
  "Bravo!",
  "Strength!",
  "Jump for Joy",
  "Triumphant Delight",
  "Fancy Spin",
  "Nod in Thought",
  "Finger Snap",
  "Rallying Cry",
  "Heartening Cry",
  "May the Best Win",
  "Bow",
  "Polite Bow",
  "As You Wish",
  "My Thanks",
  "Curtsy",
  "Reverential Bow",
  "My Lord",
  "Let Us Go Together",
  "O Mother",
  "What Do You Want?",
  "By My Sword",
  "Hoslow's Oath",
  "Fire Spur Me",
  "The Ring",
  "Ring of Miquella",
  "Erudition",
  "Prayer",
  "Desperate Prayer",
  "Rapture",
  "Inner Order",
  "Outer Order",
  "Golden Order Totality",
  "The Two Fingers",
  "Extreme Repentance",
  "Grovel for Mercy",
  "Crossed Legs",
  "Dozing Cross-Legged",
  "Rest",
  "Sitting Sideways",
  "Dejection",
  "Patches' Crouch",
  "Balled Up",
  "Spread Out",
  "Golden Seed",
  "Sacred Tear",
  "Scadutree Fragment",
  "Revered Spirit Ash",
  "Cracked Pot",
  "Ritual Pot",
  "Hefty Cracked Pot",
  "Perfume Bottle",
  "Memory Stone",
  "Talisman Pouch",
  "Bone Peddler's",
  "Meat Peddler's",
  "Medicine Peddler's",
  "Gravity Stone Peddler's Bell Bearing",
  "Smithing-Stone Miner's (1)",
  "Smithing-Stone Miner's (2)",
  "Smithing-Stone Miner's (3)",
  "Smithing-Stone Miner's (4)",
  "Somberstone Miner's (1)",
  "Somberstone Miner's (2)",
  "Somberstone Miner's (3)",
  "Somberstone Miner's (4)",
  "Somberstone Miner's (5)",
  "Glovewort Picker's (1)",
  "Glovewort Picker's (2)",
  "Glovewort Picker's (3)",
  "Ghost-Glovewort Picker's (1)",
  "Ghost-Glovewort Picker's (2)",
  "Ghost-Glovewort Picker's (3)",
  "Herbalist's",
  "Mushroom-Seller's (1)",
  "Mushroom-Seller's (2)",
  "Greasemonger's",
  "Moldmonger's",
  "Spellmachinist's",
  "String-Seller's",
  "Nomadic Warrior's Cookbook (1)",
  "Nomadic Warrior's Cookbook (2)",
  "Nomadic Warrior's Cookbook (3)",
  "Nomadic Warrior's Cookbook (4)",
  "Nomadic Warrior's Cookbook (5)",
  "Nomadic Warrior's Cookbook (6)",
  "Nomadic Warrior's Cookbook (7)",
  "Nomadic Warrior's Cookbook (8)",
  "Nomadic Warrior's Cookbook (9)",
  "Nomadic Warrior's Cookbook (10)",
  "Nomadic Warrior's Cookbook (11)",
  "Nomadic Warrior's Cookbook (12)",
  "Nomadic Warrior's Cookbook (13)",
  "Nomadic Warrior's Cookbook (14)",
  "Nomadic Warrior's Cookbook (15)",
  "Nomadic Warrior's Cookbook (16)",
  "Nomadic Warrior's Cookbook (17)",
  "Nomadic Warrior's Cookbook (18)",
  "Nomadic Warrior's Cookbook (19)",
  "Nomadic Warrior's Cookbook (20)",
  "Nomadic Warrior's Cookbook (21)",
  "Nomadic Warrior's Cookbook (22)",
  "Nomadic Warrior's Cookbook (23)",
  "Nomadic Warrior's Cookbook (24)",
  "Armorer's Cookbook (1)",
  "Armorer's Cookbook (2)",
  "Armorer's Cookbook (3)",
  "Armorer's Cookbook (4)",
  "Armorer's Cookbook (5)",
  "Armorer's Cookbook (6)",
  "Armorer's Cookbook (7)",
  "Glintstone Craftsman's Cookbook (1)",
  "Glintstone Craftsman's Cookbook (2)",
  "Glintstone Craftsman's Cookbook (3)",
  "Glintstone Craftsman's Cookbook (4)",
  "Glintstone Craftsman's Cookbook (5)",
  "Glintstone Craftsman's Cookbook (6)",
  "Glintstone Craftsman's Cookbook (7)",
  "Glintstone Craftsman's Cookbook (8)",
  "Missionary's Cookbook (1)",
  "Missionary's Cookbook (2)",
  "Missionary's Cookbook (3)",
  "Missionary's Cookbook (4)",
  "Missionary's Cookbook (5)",
  "Missionary's Cookbook (6)",
  "Missionary's Cookbook (7)",
  "Ancient Dragon Apostle's Cookbook (1)",
  "Ancient Dragon Apostle's Cookbook (2)",
  "Ancient Dragon Apostle's Cookbook (3)",
  "Ancient Dragon Apostle's Cookbook (4)",
  "Perfumer's Cookbook (1)",
  "Perfumer's Cookbook (2)",
  "Perfumer's Cookbook (3)",
  "Perfumer's Cookbook (4)",
  "Fevour's Cookbook (1)",
  "Fevour's Cookbook (2)",
  "Fevour's Cookbook (3)",
  "Frenzied's Cookbook (1)",
  "Frenzied's Cookbook (2)",
  "Great Potentate's Cookbook (1)",
  "Great Potentate's Cookbook (2)",
  "Great Potentate's Cookbook (3)",
  "Great Potentate's Cookbook (4)",
  "Great Potentate's Cookbook (5)",
  "Great Potentate's Cookbook (6)",
  "Great Potentate's Cookbook (7)",
  "Great Potentate's Cookbook (8)",
  "Great Potentate's Cookbook (9)",
  "Great Potentate's Cookbook (10)",
  "Great Potentate's Cookbook (11)",
  "Great Potentate's Cookbook (12)",
  "Great Potentate's Cookbook (13)",
  "Great Potentate's Cookbook (14)",
  "Loyal Knight's Cookbook",
  "Fire Knight's Cookbook (1)",
  "Fire Knight's Cookbook (2)",
  "Battlefield Priest's Cookbook (1)",
  "Battlefield Priest's Cookbook (2)",
  "Battlefield Priest's Cookbook (3)",
  "Battlefield Priest's Cookbook (4)",
  "Ancient Dragon Knight's Cookbook (1)",
  "Ancient Dragon Knight's Cookbook (2)",
  "St. Trina's Disciple's Cookbook (1)",
  "St. Trina's Disciple's Cookbook (2)",
  "St. Trina's Disciple's Cookbook (3)",
  "Mad Craftsman's Cookbook (1)",
  "Mad Craftsman's Cookbook (2)",
  "Mad Craftsman's Cookbook (3)",
  "Grave Keeper's Cookbook (1)",
  "Grave Keeper's Cookbook (2)",
  "Tibia's Cookbook",
  "Finger-Weaver's Cookbook (1)",
  "Finger-Weaver's Cookbook (2)",
  "Forager Brood's Cookbook (1)",
  "Forager Brood's Cookbook (2)",
  "Forager Brood's Cookbook (3)",
  "Forager Brood's Cookbook (4)",
  "Forager Brood's Cookbook (5)",
  "Forager Brood's Cookbook (6)",
  "Forager Brood's Cookbook (7)",
  "Igon's Cookbook (1)",
  "Igon's Cookbook (2)",
  "Antiquity Scholar's Cookbook (1)",
  "Antiquity Scholar's Cookbook (2)",
];

let searchbar = document.getElementById("searchbar");

//
//Dark Soulser 1
//

for (const element of lista) {
  let ciccione = document.createElement("li");
  ciccione.classList.add("sasso");
  ciccione.innerHTML = `<a target="s" rel="s" href = "https://darksouls.wiki.fextralife.com/${element}">${element}</a>`;
  document.getElementById("list").appendChild(ciccione);
}

function search_item() {
  let input = document.getElementById("searchbar").value;
  input = input.toLowerCase();
  let x = document.getElementsByClassName("sasso");
  let found = false;

  if (list.querySelector("#notfound")) {
    list.innerHTML = "";
    for (const element of lista) {
      let ciccione = document.createElement("li");
      ciccione.classList.add("sasso");
      ciccione.innerHTML = `<a target="s" rel="s" href="https://darksouls.wiki.fextralife.com/${element}">${element}</a>`;
      list.appendChild(ciccione);
    }
    x = document.getElementsByClassName("sasso");
  }

  for (const mocc of x) {
    if (mocc.textContent.toLowerCase().includes(input)) {
      mocc.style.display = "list-item";
      found = true;
    } else {
      mocc.style.display = "none";
    }
  }
  if (!found && input.trim() !== "") {
    list.innerHTML = '<li id="notfound">Item Not Found</li>';
  }
}

//
//Dark Soulser 2
//

for (const element of lista2) {
  let ciccione = document.createElement("li");
  ciccione.classList.add("sasso2");
  ciccione.innerHTML = `<a target="s" rel="s" href = "https://darksouls2.wiki.fextralife.com/${element}">${element}</a>`;
  document.getElementById("list2").appendChild(ciccione);
}

function search_item2() {
  let input = document.getElementById("searchbar2").value;
  input = input.toLowerCase();
  let x = document.getElementsByClassName("sasso2");
  let found = false;

  if (list2.querySelector("#notfound")) {
    list2.innerHTML = "";
    for (const element of lista2) {
      let ciccione = document.createElement("li");
      ciccione.classList.add("sasso2");
      ciccione.innerHTML = `<a target="s" rel="s" href="https://darksouls2.wiki.fextralife.com/${element}">${element}</a>`;
      list2.appendChild(ciccione);
    }
    x = document.getElementsByClassName("sasso2");
  }

  for (const mocc of x) {
    if (mocc.textContent.toLowerCase().includes(input)) {
      mocc.style.display = "list-item";
      found = true;
    } else {
      mocc.style.display = "none";
    }
  }
  if (!found && input.trim() !== "") {
    list2.innerHTML = '<li id="notfound">Item Not Found</li>';
  }
}

//
//Dark Soulser 3
//

for (const element of lista3) {
  let ciccione = document.createElement("li");
  ciccione.classList.add("sasso3");
  ciccione.innerHTML = `<a target="s" rel="s" href = "https://darksouls3.wiki.fextralife.com/${element}">${element}</a>`;
  document.getElementById("list3").appendChild(ciccione);
}

function search_item3() {
  let input = document.getElementById("searchbar3").value;
  input = input.toLowerCase();
  let x = document.getElementsByClassName("sasso3");
  let found = false;

  if (list3.querySelector("#notfound")) {
    list3.innerHTML = "";
    for (const element of lista3) {
      let ciccione = document.createElement("li");
      ciccione.classList.add("sasso3");
      ciccione.innerHTML = `<a target="s" rel="s" href="https://darksouls3.wiki.fextralife.com/${element}">${element}</a>`;
      list3.appendChild(ciccione);
    }
    x = document.getElementsByClassName("sasso3");
  }

  for (const mocc of x) {
    if (mocc.textContent.toLowerCase().includes(input)) {
      mocc.style.display = "list-item";
      found = true;
    } else {
      mocc.style.display = "none";
    }
  }
  if (!found && input.trim() !== "") {
    list3.innerHTML = '<li id="notfound">Item Not Found</li>';
  }
}

//
//Elden Ringer
//

for (const element of lista4) {
  let ciccione = document.createElement("li");
  ciccione.classList.add("sasso4");
  ciccione.innerHTML = `<a target="s" rel="s" href = "https://eldenring.wiki.fextralife.com/${element}">${element}</a>`;
  document.getElementById("list4").appendChild(ciccione);
}

function search_item4() {
  let input = document.getElementById("searchbar4").value;
  input = input.toLowerCase();
  let x = document.getElementsByClassName("sasso4");
  let found = false;

  if (list4.querySelector("#notfound")) {
    list4.innerHTML = "";
    for (const element of lista4) {
      let ciccione = document.createElement("li");
      ciccione.classList.add("sasso4");
      ciccione.innerHTML = `<a target="s" rel="s" href="https://eldenring.wiki.fextralife.com/${element}">${element}</a>`;
      list4.appendChild(ciccione);
    }
    x = document.getElementsByClassName("sasso4");
  }

  for (const mocc of x) {
    if (mocc.textContent.toLowerCase().includes(input)) {
      mocc.style.display = "list-item";
      found = true;
    } else {
      mocc.style.display = "none";
    }
  }
  if (!found && input.trim() !== "") {
    list4.innerHTML = '<li id="notfound">Item Not Found</li>';
  }
}
